[package]
name = "birlscript"
version = "1.2.0"
authors = ["Rafael R Nakano <lazpeng@gmail.com>"]

description = "Interpretador da linguagem BIRLSCRIPT"
repository = "https://github.com/birlscript/birlscript"

[dependencies]
meval = "^0.0.6"
